# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

WORKDIR /app

# Install apt packages (AWS CLI and dependencies)
RUN apt-get update && apt-get install -y awscli && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Copy project files
COPY . .

# Install the AWS MCP Server package
RUN pip install --no-cache-dir .

# Set default environment variables
ENV AWS_MCP_TIMEOUT=300 \
    AWS_MCP_MAX_OUTPUT=100000 \
    AWS_MCP_TRANSPORT=stdio \
    AWS_PROFILE=default \
    AWS_REGION=us-east-1

# Run the AWS MCP Server
CMD ["python", "-m", "aws_mcp_server"]
